spring.application.name=JPetStore
# ???????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/mypetstore?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# MyBatis configuration
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.csu.jpetstore.domain
mybatis.configuration.map-underscore-to-camel-case=true

# JWT
jwt.secret=JPetStore2024SecretKeyForJwtTokenGeneration
jwt.expiration=86400000

# GitHub OAuth
github.oauth.client-id=Ov23li0a03QSnysudw6A
github.oauth.client-secret=8ca850be327037b78748280a1a81d2f98935c103
github.oauth.redirect-uri=http://localhost:8080/api/v1/auth/oauth/github/callback
